/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Amenity } from "./Amenity";
import { AmenityCountArgs } from "./AmenityCountArgs";
import { AmenityFindManyArgs } from "./AmenityFindManyArgs";
import { AmenityFindUniqueArgs } from "./AmenityFindUniqueArgs";
import { DeleteAmenityArgs } from "./DeleteAmenityArgs";
import { AmenityService } from "../amenity.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Amenity)
export class AmenityResolverBase {
  constructor(
    protected readonly service: AmenityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Amenity",
    action: "read",
    possession: "any",
  })
  async _amenitiesMeta(
    @graphql.Args() args: AmenityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Amenity])
  @nestAccessControl.UseRoles({
    resource: "Amenity",
    action: "read",
    possession: "any",
  })
  async amenities(
    @graphql.Args() args: AmenityFindManyArgs
  ): Promise<Amenity[]> {
    return this.service.amenities(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Amenity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Amenity",
    action: "read",
    possession: "own",
  })
  async amenity(
    @graphql.Args() args: AmenityFindUniqueArgs
  ): Promise<Amenity | null> {
    const result = await this.service.amenity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Amenity)
  @nestAccessControl.UseRoles({
    resource: "Amenity",
    action: "delete",
    possession: "any",
  })
  async deleteAmenity(
    @graphql.Args() args: DeleteAmenityArgs
  ): Promise<Amenity | null> {
    try {
      return await this.service.deleteAmenity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
