/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Maintenance } from "./Maintenance";
import { MaintenanceCountArgs } from "./MaintenanceCountArgs";
import { MaintenanceFindManyArgs } from "./MaintenanceFindManyArgs";
import { MaintenanceFindUniqueArgs } from "./MaintenanceFindUniqueArgs";
import { DeleteMaintenanceArgs } from "./DeleteMaintenanceArgs";
import { MaintenanceService } from "../maintenance.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Maintenance)
export class MaintenanceResolverBase {
  constructor(
    protected readonly service: MaintenanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "read",
    possession: "any",
  })
  async _maintenancesMeta(
    @graphql.Args() args: MaintenanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Maintenance])
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "read",
    possession: "any",
  })
  async maintenances(
    @graphql.Args() args: MaintenanceFindManyArgs
  ): Promise<Maintenance[]> {
    return this.service.maintenances(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Maintenance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "read",
    possession: "own",
  })
  async maintenance(
    @graphql.Args() args: MaintenanceFindUniqueArgs
  ): Promise<Maintenance | null> {
    const result = await this.service.maintenance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Maintenance)
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "delete",
    possession: "any",
  })
  async deleteMaintenance(
    @graphql.Args() args: DeleteMaintenanceArgs
  ): Promise<Maintenance | null> {
    try {
      return await this.service.deleteMaintenance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
