/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReservationService } from "../reservation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReservationCreateInput } from "./ReservationCreateInput";
import { Reservation } from "./Reservation";
import { ReservationFindManyArgs } from "./ReservationFindManyArgs";
import { ReservationWhereUniqueInput } from "./ReservationWhereUniqueInput";
import { ReservationUpdateInput } from "./ReservationUpdateInput";
import { GuestFindManyArgs } from "../../guest/base/GuestFindManyArgs";
import { Guest } from "../../guest/base/Guest";
import { GuestWhereUniqueInput } from "../../guest/base/GuestWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReservationControllerBase {
  constructor(
    protected readonly service: ReservationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reservation })
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ReservationCreateInput,
  })
  async createReservation(
    @common.Body() data: ReservationCreateInput
  ): Promise<Reservation> {
    return await this.service.createReservation({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        guestId: true,
        hotelId: true,
        roomId: true,
        checkInDate: true,
        checkOutDate: true,
        numberOfGuests: true,
        reservationStatus: true,
        totalPrice: true,
        paymentStatus: true,
        bookingDate: true,
        specialRequests: true,
        confirmationNumber: true,
        cancellationDate: true,
        cancellationReason: true,
        roomTypeId: true,
        additionalServices: true,
        isPaid: true,
        lastModified: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reservation] })
  @ApiNestedQuery(ReservationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reservations(@common.Req() request: Request): Promise<Reservation[]> {
    const args = plainToClass(ReservationFindManyArgs, request.query);
    return this.service.reservations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        guestId: true,
        hotelId: true,
        roomId: true,
        checkInDate: true,
        checkOutDate: true,
        numberOfGuests: true,
        reservationStatus: true,
        totalPrice: true,
        paymentStatus: true,
        bookingDate: true,
        specialRequests: true,
        confirmationNumber: true,
        cancellationDate: true,
        cancellationReason: true,
        roomTypeId: true,
        additionalServices: true,
        isPaid: true,
        lastModified: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reservation(
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Reservation | null> {
    const result = await this.service.reservation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        guestId: true,
        hotelId: true,
        roomId: true,
        checkInDate: true,
        checkOutDate: true,
        numberOfGuests: true,
        reservationStatus: true,
        totalPrice: true,
        paymentStatus: true,
        bookingDate: true,
        specialRequests: true,
        confirmationNumber: true,
        cancellationDate: true,
        cancellationReason: true,
        roomTypeId: true,
        additionalServices: true,
        isPaid: true,
        lastModified: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ReservationUpdateInput,
  })
  async updateReservation(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() data: ReservationUpdateInput
  ): Promise<Reservation | null> {
    try {
      return await this.service.updateReservation({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          guestId: true,
          hotelId: true,
          roomId: true,
          checkInDate: true,
          checkOutDate: true,
          numberOfGuests: true,
          reservationStatus: true,
          totalPrice: true,
          paymentStatus: true,
          bookingDate: true,
          specialRequests: true,
          confirmationNumber: true,
          cancellationDate: true,
          cancellationReason: true,
          roomTypeId: true,
          additionalServices: true,
          isPaid: true,
          lastModified: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReservation(
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Reservation | null> {
    try {
      return await this.service.deleteReservation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          guestId: true,
          hotelId: true,
          roomId: true,
          checkInDate: true,
          checkOutDate: true,
          numberOfGuests: true,
          reservationStatus: true,
          totalPrice: true,
          paymentStatus: true,
          bookingDate: true,
          specialRequests: true,
          confirmationNumber: true,
          cancellationDate: true,
          cancellationReason: true,
          roomTypeId: true,
          additionalServices: true,
          isPaid: true,
          lastModified: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/guests")
  @ApiNestedQuery(GuestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "any",
  })
  async findGuests(
    @common.Req() request: Request,
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Guest[]> {
    const query = plainToClass(GuestFindManyArgs, request.query);
    const results = await this.service.findGuests(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        lastName: true,
        email: true,
        firstName: true,
        phoneNumber: true,

        reservation: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/guests")
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "update",
    possession: "any",
  })
  async connectGuests(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() body: GuestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      guests: {
        connect: body,
      },
    };
    await this.service.updateReservation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/guests")
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "update",
    possession: "any",
  })
  async updateGuests(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() body: GuestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      guests: {
        set: body,
      },
    };
    await this.service.updateReservation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/guests")
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "update",
    possession: "any",
  })
  async disconnectGuests(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() body: GuestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      guests: {
        disconnect: body,
      },
    };
    await this.service.updateReservation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
